workflow:
  rules:
    - when: always

include:
  - component: $CI_SERVER_FQDN/system/components/gitleaks/gitleaks-pipeline@0
    inputs:
      config_path: ${CI_API_V4_URL}/projects/system%2Fcomponents%2Fgitleaks/repository/files/gitleaks.toml/raw