gitleaks-validate:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
  needs: []
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/scans/gitleaks-validate.yml
    strategy: depend

trivy-validate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  needs: []
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/scans/trivy-validate.yml
    strategy: depend

opengrep-validate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  needs: []
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/scans/opengrep-validate.yml
    strategy: depend


license-scan-validate:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never
  needs: []
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/scans/license-scan-validate.yml
    strategy: depend
