gitleaks-validate:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"'
      when: always
  needs: []
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/scans/gitleaks-validate.yml
    strategy: depend

merge-policy-validate:
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: always
  trigger:
    include: .gitlab/.terraform-managed-gitlab-ci/merge-policy-validate.yml
    strategy: depend